export enum RouterNameBackground {
    AdminHome = "AdminHome",
    AdminForget = "Adminforget",
    AdminLogin = 'AdminLogin',
    AdminOrder = 'AdminOrder',
    AdminUser = 'AdminUser',
    AdminUserList = 'AdminUserList',
    // AdminUserAmount = 'AdminUserAmount',
    AdminUserAmountLog = 'AdminUserAmountLog',
    AdminUserLoginLog = 'AdminUserLoginLog',
    AdminUserWithdraw = 'AdminUserWithdraw',

    AdminShop = 'AdminShop',
    AdminShopOrder = 'AdminShopOrder',

    AdminSetting = 'AdminSetting',
    AdminSettingBase = 'AdminSettingBase',
    AdminSettingLogin = 'AdminSettingLogin',
    AdminSettingPay = 'AdminSettingPay',
    AdminSettingWithdraw = 'AdminSettingWithdraw',
    AdminSettingNotice = 'AdminSettingNotice',
    AdminSettingPageDiy = 'AdminSettingPageDiy',
    AdminSettingRealPeplo = 'AdminSettingRealPeplo',
    AdminSettingMsg = 'AdminSettingMsg',

    AdminChannel = 'AdminChannel',
    AdminChannelPay = 'AdminChannelPay',
    AdminChannelList = 'AdminChannelList',
    AdminChannelPoll = 'AdminChannelPoll',
}