export enum RouterName {
  login = "login",
  register = "register",
  forget = "forget",
  index = "index",
  home = "home",
  doc = "doc",
  test = "test",
  demo = "demo",

  // 用户中心
  userRoot = "userRoot",
  userHome = "userHome",
  userOrder = "userOrder",
  userNotifyLog = "userNotifyLog",
  userApi = "userApi",
  userInfo = "userInfo",
  userResetPwd = "userResetPwd",
  userLoginLog = "userLoginLog",
  userSafeSetting = "userSafeSetting",
  userRecharge = "userRecharge",
  userAmountLog = "userAmountLog",
  userSettleLog = "userSettleLog",
  userChannel = "userChannel",
  userPayConfig = "userPayConfig",
  userAvg = "userAvg",
  userMeal = "userMeal",
  payCenter = "payCenter",
  userChannelAccount = "userChannelAccount",
  payStatus = "payStatus",
  userCashier = "userCashier",
  cashier = "cashier",
  payChose = "payChose",
  userPayPolling = "userPayPolling",
  bt = "bt",
}
