/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Line: typeof import('./components/echarts/line.vue')['default']
    PayTypes: typeof import('./components/pay/PayTypes.vue')['default']
    RegPay: typeof import('./components/user/RegPay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XMarkdown: typeof import('./components/common/XMarkdown.vue')['default']
  }
}
